apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hans-niemann

resources:
  - ../../base
  - ingress.yaml

images:
  - name: registry.144.91.77.245.sslip.io/hans-niemann
    newName: registry.144.91.77.245.sslip.io/hans-niemann
    newTag: 06d335ffeb375f803c9c7bce6d8fd4691cb6958b

commonLabels:
  app.kubernetes.io/name: hans-niemann
  app.kubernetes.io/part-of: hans-niemann

