apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hans-niemann

resources:
  - ../../base
  - ingress.yaml

images:
  - name: registry.144.91.77.245.sslip.io/hans-niemann
    newName: registry.144.91.77.245.sslip.io/hans-niemann
    newTag: 36c17d0aa4e7ccf48ff97bbaee0e96dfd8db1888

commonLabels:
  app.kubernetes.io/name: hans-niemann
  app.kubernetes.io/part-of: hans-niemann
