apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hans-niemann

resources:
  - ../../base
  - ingress.yaml

images:
  - name: registry.144.91.77.245.sslip.io/hans-niemann
    newName: registry.144.91.77.245.sslip.io/hans-niemann
    newTag: 9afcd94959714eebe68a2746adad0e0e45f06938

commonLabels:
  app.kubernetes.io/name: hans-niemann
  app.kubernetes.io/part-of: hans-niemann

